### ISSUE TITLE
Erro refusing to allow an OAuth App to create or update workflow `.github/workflows/all.yaml` without `workflow` scope

### ISSUE THREAD

**Issue by gabrielbdornass** [gabrielbdornass/dados-sisor-2025#1]
Error during the first `git push origin main`:

```
dados-sisor-2025 git:(main) git push origin main
Enumerating objects: 1307, done.
Counting objects: 100% (1307/1307), done.
Delta compression using up to 12 threads
Compressing objects: 100% (168/168), done.
Writing objects: 100% (1307/1307), 7.12 MiB | 1.37 MiB/s, done.
Total 1307 (delta 1128), reused 1307 (delta 1128), pack-reused 0
remote: Resolving deltas: 100% (1128/1128), done.
To https://github.com/gabrielbdornass/dados-sisor-2025.git
 ! [remote rejected] main -> main (refusing to allow an OAuth App to create or update workflow `.github/workflows/all.yaml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/gabrielbdornass/dados-sisor-2025.git'
```

**Comment by gabrielbdornass** [comment]
It was necessary create a GitHub classic token with the repo scope, as some workflow steps need it:

```
    - name: Workflow failure notification
      uses: JasonEtco/create-an-issue@v2
      if: failure()
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        filename: .github/workflow-failure.md
```
